import { LaunchpadType } from "src/types/viiewPool"

const env = await import.meta.env

export const VITE_API_DOMAIN = env.VITE_API_DOMAIN
export const VITE_PROJECT_ID = env.VITE_PROJECT_ID
export const VITE_CONTRACT_STAKE = env.VITE_CONTRACT_STAKE
export const VITE_CONTRACT_TOKEN = env.VITE_CONTRACT_TOKEN
export const VITE_SIWE_DOMAIN = env.VITE_SIWE_DOMAIN
export const VITE_FAUCET_CONTRACT_ADDRESS = env.VITE_FAUCET_CONTRACT_ADDRESS
export const VITE_TINYMCE_API_KEY = env.VITE_TINYMCE_API_KEY

export const VITE_GUARANTEED_BEACON_PROXY_FACTORY = env.VITE_GUARANTEED_BEACON_PROXY_FACTORY
export const VITE_COMMUNITY_BEACON_PROXY_FACTORY = env.VITE_COMMUNITY_BEACON_PROXY_FACTORY
export const VITE_FCFS_BEACON_PROXY_FACTORY = env.VITE_FCFS_BEACON_PROXY_FACTORY

export const ProxyFactoryAddress = {
  [LaunchpadType.GUARANTEED]: VITE_GUARANTEED_BEACON_PROXY_FACTORY,
  [LaunchpadType.COMMUNITY]: VITE_COMMUNITY_BEACON_PROXY_FACTORY,
  [LaunchpadType.FCFS]: VITE_FCFS_BEACON_PROXY_FACTORY
}
